# interval
lookback: 365
horizon: 62

# dataloader
train_batch: 256
valid_batch: 512
test_batch: 512
n_workers: 3

# training
seed: 17
epochs: 20
warmup_epochs: 10
max_norm: 2

# registries
model: 
    name: "LSTM"
    parameters:
        enc_h_size: 256
        dec_h_size: 256
        n_layers: 1
        attn_type: "none"
        dropout_enc: 0.2
        dropout_dec: 0.0
        dropout_ctx: 0.5
        dropout_h: 0.005
        dropout_c: 0.005
        dropout_out: 0.3


loss: 
    name: "MAE"
    parameters: {}


optimizer: 
    name: "AdamW"
    parameters:
        lr:  0.001
        betas: [0.9, 0.999]
        weight_decay: 0.00001
        amsgrad: False


scheduler: 
    name: "CosineAnnealingLR"
    parameters:
        T_max: 20
        eta_min: 0.00001