# interval
lookback: 500
horizon: 62

# dataloader
train_batch: 128
valid_batch: 256
test_batch: 256
n_workers: 4

# training
seed: 321
epochs: 27
warmup_epochs: 7
max_norm: 2
patience: null
ema_decay: 0.99

tsp_h: 0.000001
sep_h: 0.000001

# registries
model: 
    name: "GRU_ConvAttn"
    parameters:
        enc_h_size: 256
        dec_h_size: 256
        n_layers: 1
        readout_size: 128
        fingerprint_size: 16
        attn_n_heads: 4
        dropout_enc: 0.2
        dropout_dec: 0.0
        dropout_ctx: 0.5
        dropout_h: 0.005
        dropout_c: 0.005
        dropout_out: 0.3
        readout_dropout: 0.3
        fingerprint_dropout: 0.35


loss: 
    name: "SMAPE"
    parameters: {}


optimizer: 
    name: "AdamW"
    parameters:
        lr:  0.0008
        betas: [0.9, 0.999]
        weight_decay: 0.0008
        amsgrad: False


scheduler: 
    name: "CosineAnnealingLR"
    parameters:
        T_max: 27
        eta_min: 0.0001